{
 "title": "K7BCX-10",
 "description": "PDX iGate",
 "tags": [ "aprs" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "station", "label": "station", "query": "K7BCX-10" }
  ]
 },
 "panels": [
  { "title": "current", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Welcome",
   "type": "text",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "> System: [igate.k7bcx.com](https://igate.k7bcx.com)\n* Raspbian on Raspberry Pi 5\n* Direwolf 1.7 TNC/APRS Transcoder ([full console](https://igate.k7bcx.com/direwolf))\n* Yaesu FT-2980 at **30W** on **144.39MHz** with Alinco DM-430 PSU\n* Roll-up ladder line j-pole antenna* Easy Digi Sound Card Interface \n\n> Station Info: [K7BCX-10](https://aprs.fi/info/a/K7BCX-10)\n* RF Beacon Interval: **30min WIDE1-1,WIDE2-1** \n* Contact: Billie Cleek / k7bcx at arrl dot net"
   }
  },
  {
   "title": "uploaded packets",
   "type": "stat",
   "description": "number of packets uploaded to internet server",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "direwolf.stats_dwstats_up{host=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "downloaded packets",
   "type": "stat",
   "description": "number of packets downloaded from internet server",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "direwolf.stats_dwstats_down{host=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reachable stations",
   "type": "stat",
   "description": "number of reachable stations",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "direwolf.stats_dwstats_loc{host=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "all rx",
   "type": "stat",
   "description": "stations heard in the last 30 minutes",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "direwolf.stats_dwstats_rf{host=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "direct Rx",
   "type": "stat",
   "description": "stations heard directly in the last 30 minutes",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "direwolf.stats_dwstats_dir{host=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Digi Tx",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "direwolf.stats",
     "select": [
      [
       { "params": [ "dwstats_digi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "/^$station$/" }
     ]
    }
   ]
  },
  {
   "title": "messages tx",
   "type": "stat",
   "description": "messages from the internet server that have been transmitted over the radio",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "direwolf.stats_dwstats_msg{host=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "non-message tx",
   "type": "stat",
   "description": "non-message packets received from the internet server which have been transmitted over the radio",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "direwolf.stats_dwstats_pkt{host=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dwstats_uptime_value{host=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "APRS Stations Rx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "direwolf.stats_dwstats_rf{host=\"$station\"}",
     "legendFormat": "all rf (30m lookback)"
    },
    {
     "expr": "direwolf.stats_dwstats_loc{host=\"$station\"}",
     "legendFormat": "reachable stations"
    },
    {
     "expr": "direwolf.stats_dwstats_dir{host=\"$station\"}",
     "legendFormat": "direct rx (30m lookback)"
    },
    {
     "expr": "increase(direwolf.stats_dwstats_msg{host=\"$station\"}[30m])",
     "legendFormat": "messages transmitted"
    },
    {
     "expr": "increase(direwolf.stats_dwstats_pkt{host=\"$station\"}[30m])",
     "legendFormat": "other packets transmitted"
    }
   ]
  },
  {
   "title": "APRS-IS Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(direwolf.stats_dwstats_up{host=\"$station\"}[30m])",
     "legendFormat": "sent"
    },
    {
     "expr": "increase(direwolf.stats_dwstats_down{host=\"$station\"}[30m])",
     "legendFormat": "recv"
    }
   ]
  },
  {
   "title": "Most Recent Positions Rx via RF",
   "type": "geomap",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "_time:$__range AND tags.host:$station | last 1 by (_time) partition by (tags.name) | fields fields.latitude,fields.longitude,tags.name | rename tags.name as name, fields.latitude as latitude, fields.longitude as longitude"
    }
   ]
  },
  {
   "title": "logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "DireWolf Console (Realtime)",
     "type": "text",
     "description": "[Scrollable Full Screen](https://igate.k7bcx.com)",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 48 },
     "options": {
      "content": "<iframe src=\"https://igate.k7bcx.com\" scrolling=\"no\" style=\"top:0; left:0; bottom:0; right:0; width:100%; height: 99% ;border:none; margin:0; padding:0;\"></iframe>"
     }
    }
   ]
  }
 ]
}