# # config file version
apiVersion: 1

prune: true
# # list of datasources to insert/update depending
# # on what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: VictoriaMetrics
    type: victoriametrics-datasource
    access: proxy
    url: http://localhost:8428
  - name: VictoriaLogs
    type: victorialogs-datasource
    access: proxy
    url: http://localhost:9428
