# # config file version
apiVersion: 1

prune: true
# # list of datasources to insert/update depending
# # on what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: metrics-influxql
    # <string, required> datasource type. Required
    type: influxdb
    # <string, required> access mode. direct or proxy. Required
    access: proxy
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> url
    url: http://localhost:8086
    # <string> database password, if used
    password:
    # <string> database user, if used
    user:
    # <string> database name, if used
    database:
    # <bool> enable/disable basic auth
    basicAuth:
    # <string> basic auth username
    basicAuthUser:
    # <string> basic auth password
    basicAuthPassword:
    # <bool> enable/disable with credentials headers
    withCredentials:
    # <bool> mark as default datasource. Max one per org
    isDefault:
    # <map> fields that will be converted to json and stored in json_data
    jsonData:
      dbName: __BUCKET__
      httpMode: GET
      httpHeaderName1: Authorization
    # <string> json object of data that will be encrypted.
    secureJsonData:
#     tlsCACert: "..."
#     tlsClientCert: "..."
#     tlsClientKey: "..."
#     # <openshift\kubernetes token example>
      httpHeaderValue1: "Token __TOKEN__"
#   version: 1
#   # <bool> allow users to edit datasources from the UI.
#   editable: false
  - name: VictoriaMetrics
    type: victoriametrics-datasource
    access: proxy
    url: http://localhost:8428
  - name: VictoriaLogs
    type: victorialogs-datasource
    access: proxy
    url: http://localhost:9428
